import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "intro",
    "prerequisites",
    {
      type: "category",
      label: "VS Code",
      items: [
        {
          type: "autogenerated",
          dirName: "vscode",
        },
      ],
    },
    {
      type: "category",
      label: "JetBrains",
      items: [
        {
          type: "autogenerated",
          dirName: "jetbrains",
        },
      ],
    },
    "just-do-once",
    {
      type: "category",
      label: "Examples",
      items: [
        {
          type: "autogenerated",
          dirName: "example",
        },
      ],
    },
    {
      type: "category",
      label: "Usage",
      items: [
        {
          type: "autogenerated",
          dirName: "usage",
        },
      ],
    },
    "online-sop-generator",
    {
      type: "category",
      label: "QA",
      items: [
        {
          type: "autogenerated",
          dirName: "qa",
        },
      ],
    },
  ],
};

export default sidebars;
